(function(root,factory){
  const core=factory();
  if(typeof module==='object'&&module.exports)module.exports=core;
  root.AscentraCore=core;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const SKILLS=['JavaScript','TypeScript','React','Node.js','Express.js','SQL','Git','GitHub','Python','Java','C++','C','DSA','MongoDB','MySQL','PostgreSQL','REST APIs','Docker','AWS','HTML','CSS','Statistics','Machine Learning','Pandas','Figma','Linux','Kubernetes','CI/CD','TensorFlow','Power BI','VS Code','Communication'];
  const ROLES=[
   {id:'fullstack',name:'Full-Stack Developer',cat:'Engineering',desc:'Build reliable product experiences across frontend and backend.',req:{JavaScript:75,React:70,'Node.js':70,'Express.js':60,SQL:60,'REST APIs':65,Git:50,DSA:60},pref:['TypeScript','MongoDB','Docker']},
   {id:'backend',name:'Backend Developer',cat:'Engineering',desc:'Design APIs, data services and durable server systems.',req:{'Node.js':75,'Express.js':65,SQL:70,'REST APIs':75,DSA:70,Git:50},pref:['Docker','AWS','Java']},
   {id:'frontend',name:'Frontend Developer',cat:'Engineering',desc:'Create accessible, fast and polished interface systems.',req:{JavaScript:75,React:75,HTML:70,CSS:70,Git:50},pref:['TypeScript','Figma']},
   {id:'swe',name:'Software Engineer',cat:'Engineering',desc:'Solve broad product and platform engineering problems.',req:{DSA:75,Java:65,Python:60,SQL:55,Git:60},pref:['Docker','AWS']},
   {id:'data',name:'Data Analyst',cat:'Data',desc:'Turn data into practical decisions and narratives.',req:{Python:65,SQL:75,Statistics:65,'Power BI':60,Pandas:60},pref:['Communication']},
   {id:'ml',name:'ML Engineer',cat:'Data',desc:'Build and operationalize machine learning systems.',req:{Python:75,Statistics:75,'Machine Learning':70,Pandas:70,TensorFlow:60},pref:['Docker','AWS']},
   {id:'devops',name:'Cloud / DevOps Engineer',cat:'Infrastructure',desc:'Automate reliable cloud delivery and operations.',req:{Linux:70,Docker:70,AWS:70,'CI/CD':65,Kubernetes:55},pref:['Python','Git']},
   {id:'product',name:'Product Analyst',cat:'Product',desc:'Frame customer problems through data and product judgment.',req:{SQL:65,Statistics:55,Communication:70,'Power BI':55},pref:['Figma','Python']}
  ];
  const COMPANIES=[['Northstar Systems','SaaS','fullstack,backend,frontend',7.0,0,'CSE,IT,ECE',['2022','2023','2024','2025']],['Vela Commerce','E-commerce','fullstack,frontend',6.5,0,'CSE,IT',['2021','2023','2025']],['Quanta Labs','Data platform','data,ml,backend',7.5,0,'CSE,IT,ECE',['2022','2024','2025']],['Mercury Bank','Fintech','swe,backend,data',7.0,0,'CSE,IT,ECE',['2021','2022','2023','2025']],['Aster Cloud','Cloud','devops,backend',6.5,1,'CSE,IT,ECE',['2022','2023','2024']],['Fathom Health','Health tech','fullstack,data',7.0,0,'CSE,IT',['2023','2024','2025']],['Orbit Mobility','Mobility','swe,frontend,devops',6.0,0,'CSE,IT,EEE',['2021','2023','2024']],['Beacon AI','AI research','ml,data',8.0,0,'CSE,IT',['2024','2025']],['Kindred Studio','Digital product','frontend,product',6.0,0,'Any',['2022','2023','2025']],['Summit Consulting','Consulting','data,product',6.5,0,'Any',['2021','2022','2024']],['Harbor Networks','Infrastructure','devops,swe',6.5,1,'CSE,IT,ECE',['2023','2024']],['Tandem Works','B2B software','fullstack,backend',7.0,0,'CSE,IT',['2021','2022','2023','2024','2025']]].map((x,i)=>({id:'c'+i,name:x[0],industry:x[1],roleIds:x[2].split(','),cgpa:x[3],backlogs:x[4],depts:x[5].split(','),years:x[6],pkg:(6+i*.45).toFixed(1)}));
  const EVIDENCE_WEIGHTS={profile:.35,project:.25,assessment:.25,resume:.10};
  const EVIDENCE_CAPS={resumeMention:35,resumeContext:45,projectMention:55,projectStrong:75,projectMax:85,sharedAssessment:55};
  const READINESS_WEIGHTS={skillAlignment:.50,resumeProjectEvidence:.18,academicProfile:.17,experienceEvidence:.08,campusOpportunityAlignment:.07};
  const emptyRole={id:null,name:'Not decided',cat:'',desc:'Choose a direction or Ask Ascentra AI to help you explore.',req:{},pref:[]};
  const clampScore=n=>Math.max(0,Math.min(100,Math.round(Number(n)||0)));
  const normalizedSkillText=s=>String(s||'').toLowerCase().replace(/\.js\b/g,' js').replace(/[^a-z0-9+#]+/g,' ').trim();
  function skillAliases(skill){let base=normalizedSkillText(skill),map={'javascript':['javascript','js'],'node js':['node js','nodejs','node'],'express js':['express js','expressjs','express'],'rest apis':['rest apis','rest api','restful api','restful apis','api endpoint','api endpoints','http api'],'dsa':['dsa','data structures','algorithms'],'git':['git','github']};return [...new Set([base,...(map[base]||[])])]}
  function skillInText(skill,text){let padded=` ${normalizedSkillText(text)} `;return skillAliases(skill).some(a=>padded.includes(` ${a} `))}
  function canonicalProfile(input={}){let profile=input.profile||input,stateStudent=input.student||profile.student||input,learning=input.learning||profile.learning||{},resume=input.resume||profile.resume||{};return {student:{...stateStudent,skills:{...(stateStudent.skills||stateStudent.technical_skills||{})},projects:stateStudent.projects||[],internships:stateStudent.internships||0,certifications:stateStudent.certifications||[],roadmap:stateStudent.roadmap||{},customRoadmapActions:stateStudent.customRoadmapActions||[]},resume,learning}}
  function roleById(roleOrId,roles=ROLES){return typeof roleOrId==='string'?(roles.find(x=>x.id===roleOrId)||emptyRole):(roleOrId||emptyRole)}
  function targetRole(profile,roles=ROLES){let cp=canonicalProfile(profile);return roleById(cp.student.target||cp.student.target_role,roles)}
  function profileEvidenceForSkill(skill,ctx){let student=canonicalProfile(ctx).student,has=Object.hasOwn(student.skills||{},skill),score=clampScore(student.skills?.[skill]);return {available:has&&score>0,score:has?score:0,label:'Profile/base score',quality:has?'profile':'not_provided',details:has?`Saved profile skill score is ${score}%. Provenance is not verified by ASCENTRA.`:'No saved profile score.'}}
  function resumeEvidenceForSkill(skill,ctx){let parsed=canonicalProfile(ctx).resume?.parsed||{},skills=parsed.skills||[],text=String(parsed.text||''),mentioned=skills.some(x=>normalizedSkillText(x)===normalizedSkillText(skill)||skillInText(skill,x)),context=(parsed.projects||[]).some(p=>skillInText(skill,p))||skillInText(skill,parsed.sections?.experience||'')||(/project|experience|internship/i.test(text)&&skillInText(skill,text));let score=context?EVIDENCE_CAPS.resumeContext:mentioned?EVIDENCE_CAPS.resumeMention:0;return {available:score>0,score,label:'Resume evidence',quality:context?'contextual':mentioned?'keyword':'not_found',details:context?`Resume references ${skill} in project or experience context; capped at ${score}%.`:mentioned?`Resume lists or mentions ${skill}; capped at ${score}% because a keyword is only a claim signal.`:'No resume evidence found.'}}
  function projectEvidenceForSkill(skill,ctx){let student=canonicalProfile(ctx).student,matches=(student.projects||[]).map(p=>({project:p,strong:skillInText(skill,p.tech||p.stack||p.technologies||'')||skillInText(skill,p.detail||'')&&/built|implemented|deployed|api|database|frontend|backend|component|server|model|query/i.test(String(p.detail||''))})).filter(x=>skillInText(skill,`${x.project.name||''} ${x.project.detail||''} ${x.project.tech||''} ${x.project.stack||''} ${x.project.technologies||''}`));if(!matches.length)return {available:false,score:0,label:'Project evidence',quality:'not_found',details:'No saved project evidence found.'};let strong=matches.some(x=>x.strong),score=(strong?EVIDENCE_CAPS.projectStrong:EVIDENCE_CAPS.projectMention)+Math.min(10,(matches.length-1)*5);score=Math.min(EVIDENCE_CAPS.projectMax,score);return {available:true,score,label:'Project evidence',quality:strong?'applied':'mentioned',count:matches.length,projects:matches.map(x=>x.project.name).filter(Boolean),details:`${matches.length} saved project${matches.length>1?'s':''} reference ${skill}; project evidence score ${score}%.`}}
  function assessmentEvidenceForSkill(skill,ctx){let learning=canonicalProfile(ctx).learning,entries=[...(learning.quizHistory||[]),learning.lastQuiz].filter(Boolean).reverse(),hit=entries.find(q=>(q.skills||[]).some(s=>normalizedSkillText(s)===normalizedSkillText(skill)||skillInText(skill,s)));if(!hit)return {available:false,score:0,label:'Weekly assessment',quality:'not_validated',details:'Weekly Skill Check not validated for this skill.'};let per=hit.perSkillScores||hit.skillScores||{},key=Object.keys(per).find(k=>normalizedSkillText(k)===normalizedSkillText(skill)||skillInText(skill,k)),raw=key!=null?per[key]:hit.score,score=clampScore(raw),shared=key==null;if(shared)score=Math.min(score,EVIDENCE_CAPS.sharedAssessment);else score=Math.min(score,EVIDENCE_CAPS.sharedAssessment);let result=(hit.questions||[]).find(q=>normalizedSkillText(q.skill)===normalizedSkillText(skill)||skillInText(skill,q.skill));return {available:score>0,score,label:'Weekly assessment',quality:shared?'shared_quiz':'per_skill',correct:result?.correct,questionId:result?.id,details:shared?`Weekly Skill Check included ${skill}, but only a shared quiz score is stored; capped at ${score}%.`:`Weekly Skill Check tested ${skill} ${result?.correct===false?'incorrectly':'directly'}; supporting assessment evidence capped at ${score}%.`}}
  function roadmapEvidenceForSkill(skill,roleOrId,ctx){let cp=canonicalProfile(ctx),r=roleById(roleOrId);let done=!!cp.student.roadmap?.[`${r.id}-${skill}`];return {available:false,score:0,label:'Roadmap activity',quality:done?'completed':'not_completed',details:done?'A related roadmap action is completed. Completion records activity only and is not counted as skill evidence.':'No completed roadmap action for this skill.'}}
  function evidenceConfidenceFrom(sources){let q=0;if(sources.profile.available)q+=1.25;if(sources.project.available)q+=sources.project.quality==='applied'?1.75:1.25;if(sources.assessment.available)q+=sources.assessment.quality==='per_skill'?2:1.5;if(sources.resume.available)q+=sources.resume.quality==='contextual'?1:.5;return q>=3?'High':q>=1.25?'Medium':'Low'}
  function getSkillEvidence(skill,roleOrId,ctx){let r=roleById(roleOrId),roleRequirement=r.req?.[skill]||0,sources={profile:profileEvidenceForSkill(skill,ctx),project:projectEvidenceForSkill(skill,ctx),assessment:assessmentEvidenceForSkill(skill,ctx),resume:resumeEvidenceForSkill(skill,ctx),roadmap:roadmapEvidenceForSkill(skill,r,ctx)},available=Object.entries(sources).filter(([k,v])=>k!=='roadmap'&&v.available&&v.score>0),weight=available.reduce((n,[k])=>n+(EVIDENCE_WEIGHTS[k]||0),0),weighted=weight?available.reduce((n,[k,v])=>n+(EVIDENCE_WEIGHTS[k]||0)*v.score,0)/weight:0,onlyResume=available.length===1&&available[0][0]==='resume';let evidenceScore=Math.max(sources.profile.available?sources.profile.score:0,Math.round(weighted));if(onlyResume&&roleRequirement>0)evidenceScore=Math.min(evidenceScore,roleRequirement-1);let gap=Math.max(0,roleRequirement-evidenceScore),label=!available.length?'No evidence yet':evidenceScore>=roleRequirement?'Ready':evidenceScore>=roleRequirement*.6?'Developing':'Priority gap',className=label==='Ready'?'ready':label==='Developing'?'developing':label==='Priority gap'?'priority':'empty',confidence=evidenceConfidenceFrom(sources),statusReason=label==='No evidence yet'?`${skill} has no meaningful saved evidence yet.`:label==='Ready'?`${skill} meets the ${r.name} requirement using the available evidence estimate.`:label==='Developing'?`${skill} has meaningful evidence, but it is still below the ${r.name} requirement.`:`${skill} remains substantially below the ${r.name} requirement.`,sourceLines=Object.values(sources).map(x=>x.details);return {skill,roleId:r.id,roleName:r.name,roleRequirement,need:roleRequirement,baseSkillScore:sources.profile.score,resumeEvidence:sources.resume,projectEvidence:sources.project,assessmentEvidence:sources.assessment,roadmapEvidence:sources.roadmap,evidenceScore,current:evidenceScore,evidenceConfidence:confidence,gap,status:label,label,className,reasons:[statusReason,...sourceLines],sources,weights:EVIDENCE_WEIGHTS,meaningfulEvidence:available.map(([k])=>k)}}
  function relevantCompanies(roleOrId,companies=COMPANIES){let r=roleById(roleOrId);return companies.filter(c=>c.roleIds.includes(r.id))}
  function normalizeDepartment(value){let t=String(value||'').toUpperCase().replace(/[^A-Z0-9]+/g,' ');if(!t)return '';if(/\b(CSE|COMPUTER SCIENCE|CS)\b/.test(t))return 'CSE';if(/\bIT\b|INFORMATION TECHNOLOGY/.test(t))return 'IT';if(/\bECE\b|ELECTRONICS.*COMM/.test(t))return 'ECE';if(/\bEEE\b|ELECTRICAL.*ELECTRONICS/.test(t))return 'EEE';if(/\bME\b|MECHANICAL/.test(t))return 'ME';if(/\bCE\b|CIVIL/.test(t))return 'CE';return t.trim()}
  function departmentPass(studentDept,allowed=[]){if(allowed.includes('Any'))return true;let fam=normalizeDepartment(studentDept);return allowed.some(x=>normalizeDepartment(x)===fam)}
  function roleScore(roleOrId,ctx){let r=roleById(roleOrId),total=0,weight=0;for(const[s,need]of Object.entries(r.req||{})){weight+=need;total+=Math.min(1,getSkillEvidence(s,r,ctx).evidenceScore/need)*need}return weight?Math.round(Math.max(0,Math.min(100,total/weight*100))):0}
  function eligibility(company,roleOrId,ctx){let cp=canonicalProfile(ctx),s=cp.student,r=roleById(roleOrId),passed=[],failed=[];let dept=departmentPass(s.department||s.branch,company.depts);(dept?passed:failed).push('department');let back=(s.backlogs||0)<=company.backlogs;(back?passed:failed).push('backlogs');let cgpa=Number(s.cgpa)>=company.cgpa;(cgpa?passed:failed).push('cgpa');let roleAvailable=company.roleIds.includes(r.id);(roleAvailable?passed:failed).push('target role');let preparationGaps=Object.entries(r.req||{}).filter(([k,v])=>getSkillEvidence(k,r,ctx).evidenceScore<v).map(([k])=>k);let status='ELIGIBLE',reason='Meets configured application rules';if(!dept||!back||!roleAvailable){status='NOT ELIGIBLE';reason='Department, backlog, or role availability rule not met'}else if(!cgpa){status=Number(s.cgpa)>=company.cgpa-.35?'NEAR ELIGIBILITY':'NOT ELIGIBLE';reason=`CGPA ${s.cgpa} vs required ${company.cgpa}`}return [status,reason,{eligible:status==='ELIGIBLE',profileFit:roleScore(r,ctx),passed,failed,reasons:[reason],missingSkills:preparationGaps,preparationGaps,departmentFamily:normalizeDepartment(s.department||s.branch)}]}
  function campus(roleOrId,ctx,companies=COMPANIES){let r=roleById(roleOrId),cs=relevantCompanies(r,companies),eligible=cs.filter(c=>eligibility(c,r,ctx)[0]!=='NOT ELIGIBLE').length;return Math.min(99,Math.round((cs.length/7*48)+(eligible/Math.max(cs.length,1)*32)+roleScore(r,ctx)*.2))}
  function gaps(roleOrId,ctx,companies=COMPANIES){let r=roleById(roleOrId),demand=relevantCompanies(r,companies).length;return Object.entries(r.req||{}).map(([name,need])=>{let ev=getSkillEvidence(name,r,ctx),gap=Math.max(0,need-ev.evidenceScore);return {name,skill:name,current:ev.evidenceScore,need,requirement:need,gap,impact:Math.round(gap/need*need*(1+demand/12)),confidence:ev.evidenceConfidence,status:ev.status,evidence:ev}}).filter(x=>x.gap>0).sort((a,b)=>b.impact-a.impact)}
  function readinessParts(roleOrId,ctx,companies=COMPANIES){let cp=canonicalProfile(ctx),s=cp.student,r=roleById(roleOrId),projectMatches=(s.projects||[]).filter(p=>Object.keys(r.req||{}).some(skill=>skillInText(skill,p.detail||''))).length,parts={skillAlignment:roleScore(r,ctx),resumeProjectEvidence:Math.min(100,(s.projects||[]).length*35+projectMatches*20),academicProfile:Math.max(0,Math.min(100,((s.cgpa||0)/8)*100-((s.backlogs||0)*15))),experienceEvidence:Math.min(100,(s.internships||0)*55+(s.certifications||[]).length*15),campusOpportunityAlignment:campus(r,ctx,companies)};parts.total=Math.round(parts.skillAlignment*READINESS_WEIGHTS.skillAlignment+parts.resumeProjectEvidence*READINESS_WEIGHTS.resumeProjectEvidence+parts.academicProfile*READINESS_WEIGHTS.academicProfile+parts.experienceEvidence*READINESS_WEIGHTS.experienceEvidence+parts.campusOpportunityAlignment*READINESS_WEIGHTS.campusOpportunityAlignment);return parts}
  const roadmapTitle=skill=>/REST APIs|Express|Node|SQL/i.test(skill)?`Build ${skill} evidence`:/React|HTML|CSS|JavaScript|TypeScript/i.test(skill)?`Strengthen ${skill} product evidence`:/DSA/i.test(skill)?'Strengthen DSA fundamentals':/Git|GitHub/i.test(skill)?`Make ${skill} evidence visible`:/Statistics|Machine Learning|Pandas|TensorFlow|Power BI/i.test(skill)?`Create ${skill} proof`:`Strengthen ${skill} evidence`;
  function roadmap(roleOrId,ctx,companies=COMPANIES){let r=roleById(roleOrId),cp=canonicalProfile(ctx),gs=gaps(r,ctx,companies),phases=[['Highest priority',gs.slice(0,2)],['Secondary priorities',gs.slice(2,5)],['Remaining priorities',gs.slice(5)]];return phases.filter(([,x])=>x.length).map(([name,items],i)=>({id:'p'+i,name,items:items.map(x=>({id:r.id+'-'+x.name,name:roadmapTitle(x.name),skill:x.name,need:x.need,current:x.current,gap:x.gap,status:x.status,confidence:x.confidence,done:!!cp.student.roadmap[r.id+'-'+x.name]}))}))}
  function roleMatch(roleOrId,ctx,companies=COMPANIES){let r=roleById(roleOrId),evidence=Object.keys(r.req||{}).map(s=>getSkillEvidence(s,r,ctx));return {role_id:r.id,roleId:r.id,role_title:r.name,roleTitle:r.name,match_score:roleScore(r,ctx),readiness:readinessParts(r,ctx,companies).total,skill_evidence:evidence,gaps:gaps(r,ctx,companies),strong_matches:evidence.filter(x=>x.evidenceScore>=x.roleRequirement).map(x=>x.skill),developing_skills:evidence.filter(x=>x.status==='Developing').map(x=>x.skill),missing_skills:evidence.filter(x=>x.status==='Priority gap'||x.status==='No evidence yet').map(x=>x.skill),explanation:'Evidence-based compatibility estimate from canonical ASCENTRA Core Intelligence; not a hiring probability.'}}
  return {SKILLS,ROLES,COMPANIES,EVIDENCE_WEIGHTS,EVIDENCE_CAPS,READINESS_WEIGHTS,canonicalProfile,roleById,targetRole,clampScore,normalizedSkillText,skillAliases,skillInText,normalizeDepartment,departmentPass,getSkillEvidence,roleScore,gaps,readinessParts,readiness:(roleOrId,ctx,companies)=>readinessParts(roleOrId,ctx,companies).total,relevantCompanies,eligibility,campus,roadmap,roadmapTitle,roleMatch};
});
